"""Centralized Telephony Metric Definitions and Catalog Specification.

Task 3: Precise Metric Definitions with exact numerators, denominators,
applicable status sets, and mathematical formulas.
"""

from typing import Dict, Any

METRIC_DEFINITIONS: Dict[str, Dict[str, Any]] = {
    "total_incoming_calls": {
        "name": "Total Incoming Calls",
        "description": "Total count of inbound PSTN and simulated call sessions initiated within the reporting window.",
        "numerator": "Count of Call records where direction == 'inbound' within date range.",
        "denominator": "None (Absolute Count)",
        "applicable_statuses": ["RINGING", "ANSWERED", "SCREENING", "CLASSIFIED", "TRANSFERRING", "COMPLETED", "FLAGGED", "NEEDS_REVIEW", "FAILED", "MISSED", "ABANDONED"],
    },
    "answered_calls": {
        "name": "Answered Calls",
        "description": "Calls successfully answered by either AI Virtual Receptionist or human operator.",
        "numerator": "Count of Call records where status in ['ANSWERED', 'SCREENING', 'CLASSIFIED', 'TRANSFERRING', 'COMPLETED', 'FLAGGED'].",
        "denominator": "total_incoming_calls",
        "applicable_statuses": ["ANSWERED", "SCREENING", "CLASSIFIED", "TRANSFERRING", "COMPLETED", "FLAGGED"],
    },
    "missed_calls": {
        "name": "Missed Calls",
        "description": "Inbound calls that rang without AI or human pick-up.",
        "numerator": "Count of Call records where status == 'MISSED'.",
        "denominator": "total_incoming_calls",
        "applicable_statuses": ["MISSED"],
    },
    "abandoned_calls": {
        "name": "Abandoned Calls",
        "description": "Calls hung up by caller during greeting or initial IVR phase before intent processing.",
        "numerator": "Count of Call records where status == 'ABANDONED' or (status == 'RINGING' and duration_seconds < 3).",
        "denominator": "total_incoming_calls",
        "applicable_statuses": ["ABANDONED"],
    },
    "completed_calls": {
        "name": "Completed Calls",
        "description": "Calls that completed dialogue lifecycle normally without abrupt termination or error.",
        "numerator": "Count of Call records where status == 'COMPLETED'.",
        "denominator": "total_incoming_calls",
        "applicable_statuses": ["COMPLETED"],
    },
    "failed_calls": {
        "name": "Failed Calls",
        "description": "Calls terminated due to carrier SIP errors, audio stream failures, or system errors.",
        "numerator": "Count of Call records where status == 'FAILED'.",
        "denominator": "total_incoming_calls",
        "applicable_statuses": ["FAILED"],
    },
    "simulated_calls": {
        "name": "Simulated Calls",
        "description": "Synthetic calls initiated via Free Browser Call Simulator or CLI diagnostic tools.",
        "numerator": "Count of Call records where external_call_sid starts with 'SIM' or telephony_provider == 'mock'.",
        "denominator": "total_incoming_calls",
        "applicable_statuses": ["ALL"],
    },
    "real_telephone_calls": {
        "name": "Real Telephone Calls",
        "description": "Genuine PSTN calls originating from carrier DIDs (e.g. Twilio, Exotel).",
        "numerator": "Count of Call records where external_call_sid does NOT start with 'SIM' and telephony_provider != 'mock'.",
        "denominator": "total_incoming_calls",
        "applicable_statuses": ["ALL"],
    },
    "calls_screened_by_ai": {
        "name": "Calls Screened by AI",
        "description": "Calls evaluated by AI dialogue engine and multi-signal spam shield.",
        "numerator": "Count of Call records with associated SpamAssessment or status in ['SCREENING', 'CLASSIFIED'].",
        "denominator": "total_incoming_calls",
        "applicable_statuses": ["SCREENING", "CLASSIFIED", "COMPLETED", "FLAGGED"],
    },
    "calls_flagged_for_review": {
        "name": "Calls Flagged for Review",
        "description": "Calls with uncertain spam score (40–69) queued for human operator review.",
        "numerator": "Count of Call records where disposition == 'uncertain' or status == 'NEEDS_REVIEW'.",
        "denominator": "total_incoming_calls",
        "applicable_statuses": ["FLAGGED", "NEEDS_REVIEW"],
    },
    "confirmed_spam_calls": {
        "name": "Human-Confirmed Spam Calls",
        "description": "Calls verified as spam/scam by human operator review.",
        "numerator": "Count of SpamReport records where review_decision == 'confirmed_spam'.",
        "denominator": "calls_flagged_for_review",
        "applicable_statuses": ["FLAGGED", "COMPLETED"],
    },
    "confirmed_legitimate_calls": {
        "name": "Human-Confirmed Legitimate Calls",
        "description": "Calls verified as legitimate by human operator review (cleared false positives).",
        "numerator": "Count of SpamReport records where review_decision == 'false_positive'.",
        "denominator": "calls_flagged_for_review",
        "applicable_statuses": ["FLAGGED", "COMPLETED"],
    },
    "pending_spam_reviews": {
        "name": "Pending Spam Reviews",
        "description": "Flagged calls currently awaiting operator review decision.",
        "numerator": "Count of flagged calls where no SpamReport decision has been filed.",
        "denominator": "calls_flagged_for_review",
        "applicable_statuses": ["NEEDS_REVIEW", "FLAGGED"],
    },
    "transfer_attempts": {
        "name": "Transfer Attempts",
        "description": "Total number of warm or blind transfer attempts initiated towards recipients.",
        "numerator": "Count of TransferRecord entries.",
        "denominator": "None (Absolute Count)",
        "applicable_statuses": ["ALL"],
    },
    "successful_transfers": {
        "name": "Successful Transfers",
        "description": "Transfers accepted by recipient and successfully bridged.",
        "numerator": "Count of TransferRecord entries where transfer_status in ['ACCEPTED', 'CONNECTED'].",
        "denominator": "transfer_attempts",
        "applicable_statuses": ["ACCEPTED", "CONNECTED"],
    },
    "declined_transfers": {
        "name": "Declined Transfers",
        "description": "Transfers manually declined by recipient pressing 2.",
        "numerator": "Count of TransferRecord entries where transfer_status == 'DECLINED'.",
        "denominator": "transfer_attempts",
        "applicable_statuses": ["DECLINED"],
    },
    "unanswered_transfers": {
        "name": "Unanswered Transfers",
        "description": "Transfers where recipient phone rang out without answer or hit busy signal.",
        "numerator": "Count of TransferRecord entries where transfer_status in ['NO_ANSWER', 'BUSY'].",
        "denominator": "transfer_attempts",
        "applicable_statuses": ["NO_ANSWER", "BUSY"],
    },
    "failed_transfers": {
        "name": "Failed Transfers",
        "description": "Transfers failed due to SIP trunk issues or toll fraud blocks.",
        "numerator": "Count of TransferRecord entries where transfer_status == 'FAILED'.",
        "denominator": "transfer_attempts",
        "applicable_statuses": ["FAILED"],
    },
    "average_call_duration": {
        "name": "Average Call Duration (seconds)",
        "description": "Average duration of inbound calls in seconds.",
        "numerator": "Sum of duration_seconds for answered calls.",
        "denominator": "Count of answered calls.",
        "applicable_statuses": ["COMPLETED", "ANSWERED", "TRANSFERRING"],
    },
    "voicemail_count": {
        "name": "Voicemail Count",
        "description": "Total voicemail recordings received.",
        "numerator": "Count of VoicemailMessage records.",
        "denominator": "None",
        "applicable_statuses": ["ALL"],
    },
    "pending_callbacks": {
        "name": "Pending Callback Requests",
        "description": "Caller return requests awaiting operator assignment or callback execution.",
        "numerator": "Count of CallbackRequest records where status == 'pending'.",
        "denominator": "Total CallbackRequest count.",
        "applicable_statuses": ["pending"],
    },
    "completed_callbacks": {
        "name": "Completed Callback Requests",
        "description": "Callback requests successfully resolved by operators.",
        "numerator": "Count of CallbackRequest records where status == 'completed'.",
        "denominator": "Total CallbackRequest count.",
        "applicable_statuses": ["completed"],
    },
}
